<?php

namespace App\Mail;

use App\Models\Order;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Attachment;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class OrderConfirmationMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(public readonly Order $order) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: "Order Confirmation — {$this->order->order_number}",
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.order_confirmation',
        );
    }

    /**
     * Attach a PDF receipt generated by DomPDF.
     */
    public function attachments(): array
    {
        $pdf = Pdf::loadView('emails.order_receipt_pdf', ['order' => $this->order]);

        return [
            Attachment::fromData(
                fn () => $pdf->output(),
                "receipt-{$this->order->order_number}.pdf"
            )->withMime('application/pdf'),
        ];
    }
}
